"""
NovaMed SFE — Component 3: Rep Efficiency Ratio & Performance Quadrant
========================================================================
For each of the 120 reps, calculates:

1. Efficiency Ratio = Actual Rx / Expected Rx
   - Actual Rx: Total prescriptions generated by the rep's visited HCPs
   - Expected Rx: Sum of potential_scores for the rep's visited HCPs × scaling constant
   - The scaling constant is calibrated so the MEDIAN rep has an efficiency ratio
     near 1.0, making the metric immediately interpretable:
       > 1.0 = outperforming territory potential
       < 1.0 = underperforming territory potential

   WHY this matters: Raw Rx volume unfairly penalizes reps in low-potential
   territories. A rep generating 500 Rx in a low-potential Tier3 city may be
   performing better than a rep generating 2,000 Rx in a high-potential Tier1
   city. The efficiency ratio normalizes for territory quality.

2. Performance Quadrant:
   - X-axis: Visit Intensity (visits per HCP per month)
   - Y-axis: Efficiency Ratio

   Four quadrants (split at the median of each axis):
   ┌─────────────────────────┬─────────────────────────┐
   │  Low Effort, High Impact│ High Effort, High Impact│
   │  (Star performers —     │ (Keep & reward — effort  │
   │   possibly under-       │  is translating to       │
   │   resourced, give more) │  results)                │
   ├─────────────────────────┼─────────────────────────┤
   │  Low Effort, Low Impact │ High Effort, Low Impact  │
   │  (Urgent intervention — │ (Investigate — wrong     │
   │   low engagement AND    │  territory or wrong      │
   │   low results)          │  targeting?)             │
   └─────────────────────────┴─────────────────────────┘

Output:
  - data/processed/rep_efficiency.csv (per-rep efficiency metrics)
  - data/processed/rep_quadrant.csv (quadrant assignments)
  - outputs/charts/rep_quadrant.png (scatter plot)

Author: Aditya (NovaMed SFE Portfolio Project)
"""

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib
matplotlib.use('Agg')  # Non-interactive backend for saving charts

# ============================================================================
# CONFIGURATION
# ============================================================================

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RAW_DIR = os.path.join(BASE_DIR, 'data', 'raw')
PROCESSED_DIR = os.path.join(BASE_DIR, 'data', 'processed')
CHARTS_DIR = os.path.join(BASE_DIR, 'outputs', 'charts')
os.makedirs(PROCESSED_DIR, exist_ok=True)
os.makedirs(CHARTS_DIR, exist_ok=True)

# Total months in the study period (Jul 2023 – Dec 2024)
TOTAL_MONTHS = 18


# ============================================================================
# MAIN — Compute Rep Efficiency and Quadrant
# ============================================================================

def compute_rep_efficiency():
    """
    Computes efficiency ratio and visit intensity for each rep,
    then assigns performance quadrant labels.
    """
    # Load data
    reps = pd.read_csv(os.path.join(RAW_DIR, 'reps.csv'))
    hcps = pd.read_csv(os.path.join(RAW_DIR, 'hcps.csv'))
    visits = pd.read_csv(os.path.join(RAW_DIR, 'visit_logs.csv'))
    rx = pd.read_csv(os.path.join(RAW_DIR, 'rx_volume.csv'))
    
    print(f"  Loaded: {len(reps)} reps, {len(hcps)} HCPs, {len(visits):,} visits, {len(rx):,} Rx records")
    
    # ------------------------------------------------------------------
    # Step 1: Identify which HCPs each rep visits (rep-HCP mapping)
    # ------------------------------------------------------------------
    rep_hcp_pairs = visits[['rep_id', 'hcp_id']].drop_duplicates()
    print(f"  Unique rep-HCP pairs: {len(rep_hcp_pairs):,}")
    
    # ------------------------------------------------------------------
    # Step 2: Calculate ACTUAL Rx per rep
    # ------------------------------------------------------------------
    # Attribution model: A rep's "actual Rx" is the total Rx volume from
    # all HCPs they visited, for the drug the rep promotes.
    # This is a common pharma SFE attribution approach — the rep gets
    # credit for the Rx volume of doctors they call on.
    
    rep_hcp_with_drug = rep_hcp_pairs.merge(
        reps[['rep_id', 'drug_focus']], on='rep_id'
    )
    
    # Total Rx per HCP per drug (all months)
    hcp_rx_total = rx.groupby(['hcp_id', 'drug_name'])['rx_count'].sum().reset_index()
    hcp_rx_total.columns = ['hcp_id', 'drug_name', 'total_rx']
    
    # Join to get Rx for each rep's HCPs (matching drug focus)
    rep_rx = rep_hcp_with_drug.merge(
        hcp_rx_total, 
        left_on=['hcp_id', 'drug_focus'],
        right_on=['hcp_id', 'drug_name'],
        how='left'
    )
    rep_rx['total_rx'] = rep_rx['total_rx'].fillna(0)
    
    actual_rx_per_rep = rep_rx.groupby('rep_id')['total_rx'].sum().reset_index()
    actual_rx_per_rep.columns = ['rep_id', 'actual_rx']
    
    # ------------------------------------------------------------------
    # Step 3: Calculate EXPECTED Rx per rep (potential-adjusted)
    # ------------------------------------------------------------------
    # Expected Rx = sum of potential_scores for the rep's visited HCPs
    # This represents the territory quality — a rep visiting high-potential
    # HCPs has a higher "expected" Rx baseline.
    
    rep_hcp_potential = rep_hcp_pairs.merge(
        hcps[['hcp_id', 'potential_score']], on='hcp_id'
    )
    
    expected_per_rep = rep_hcp_potential.groupby('rep_id')['potential_score'].sum().reset_index()
    expected_per_rep.columns = ['rep_id', 'total_potential']
    
    # ------------------------------------------------------------------
    # Step 4: Calculate Visit Intensity (visits per HCP per month)
    # ------------------------------------------------------------------
    # Visit intensity = total visits / (unique HCPs visited × total months)
    # This measures how frequently on average each of a rep's HCPs is visited
    
    visits_per_rep = visits.groupby('rep_id').agg(
        total_visits=('visit_id', 'count'),
        unique_hcps=('hcp_id', 'nunique')
    ).reset_index()
    
    visits_per_rep['visit_intensity'] = (
        visits_per_rep['total_visits'] / 
        (visits_per_rep['unique_hcps'] * TOTAL_MONTHS)
    ).round(3)
    
    # ------------------------------------------------------------------
    # Step 5: Combine and compute efficiency ratio
    # ------------------------------------------------------------------
    efficiency = reps[['rep_id', 'rep_name', 'city', 'region', 'drug_focus', 'tenure_years']].copy()
    efficiency = efficiency.merge(actual_rx_per_rep, on='rep_id', how='left')
    efficiency = efficiency.merge(expected_per_rep, on='rep_id', how='left')
    efficiency = efficiency.merge(visits_per_rep, on='rep_id', how='left')
    
    # Scaling constant: calibrate so median efficiency ratio ≈ 1.0
    # Formula: scaling_constant = median(actual_rx) / median(total_potential)
    #
    # Analytical judgment: Using median rather than mean makes the calibration
    # robust to outliers (a few reps with extremely high/low volumes won't
    # skew the baseline for everyone).
    scaling_constant = (
        efficiency['actual_rx'].median() / efficiency['total_potential'].median()
    )
    print(f"\n  Scaling constant: {scaling_constant:.4f}")
    print(f"  (Median actual Rx: {efficiency['actual_rx'].median():,.0f}, "
          f"Median total potential: {efficiency['total_potential'].median():,.0f})")
    
    efficiency['expected_rx'] = efficiency['total_potential'] * scaling_constant
    efficiency['efficiency_ratio'] = (
        efficiency['actual_rx'] / efficiency['expected_rx']
    ).round(3)
    
    # ------------------------------------------------------------------
    # Step 6: Assign performance quadrant
    # ------------------------------------------------------------------
    # Thresholds: median of each axis splits reps into 4 roughly equal groups.
    # Using median is the standard approach for quadrant analysis because:
    # 1. It's robust to outliers (unlike mean)
    # 2. It guarantees ~50/50 splits on each axis
    # 3. It's easily explainable: "above/below the typical rep"
    
    visit_median = efficiency['visit_intensity'].median()
    efficiency_median = efficiency['efficiency_ratio'].median()
    
    print(f"  Visit intensity median: {visit_median:.3f} visits/HCP/month")
    print(f"  Efficiency ratio median: {efficiency_median:.3f}")
    
    def assign_quadrant(row):
        high_effort = row['visit_intensity'] >= visit_median
        high_impact = row['efficiency_ratio'] >= efficiency_median
        
        if high_effort and high_impact:
            return 'High Effort, High Impact'
        elif high_effort and not high_impact:
            return 'High Effort, Low Impact'
        elif not high_effort and high_impact:
            return 'Low Effort, High Impact'
        else:
            return 'Low Effort, Low Impact'
    
    efficiency['performance_quadrant'] = efficiency.apply(assign_quadrant, axis=1)
    
    # ------------------------------------------------------------------
    # Save outputs
    # ------------------------------------------------------------------
    efficiency_path = os.path.join(PROCESSED_DIR, 'rep_efficiency.csv')
    efficiency.to_csv(efficiency_path, index=False)
    
    quadrant_path = os.path.join(PROCESSED_DIR, 'rep_quadrant.csv')
    efficiency.to_csv(quadrant_path, index=False)
    
    return efficiency, visit_median, efficiency_median


def plot_quadrant(efficiency_df, visit_median, efficiency_median):
    """
    Creates a professional scatter plot of the performance quadrant.
    Each rep is a dot, colored by region, positioned by visit intensity
    and efficiency ratio.
    """
    fig, ax = plt.subplots(figsize=(14, 10))
    
    # Color palette by region — professional, distinct colors
    region_colors = {
        'North': '#2E86AB',   # Steel blue
        'South': '#A23B72',   # Berry
        'East':  '#F18F01',   # Amber
        'West':  '#C73E1D'    # Rust red
    }
    
    # Plot each region's reps
    for region, color in region_colors.items():
        mask = efficiency_df['region'] == region
        subset = efficiency_df[mask]
        ax.scatter(
            subset['visit_intensity'],
            subset['efficiency_ratio'],
            c=color, label=region, alpha=0.7, s=70,
            edgecolors='white', linewidth=0.5, zorder=3
        )
    
    # Draw quadrant lines at the median
    ax.axvline(x=visit_median, color='#555555', linestyle='--', linewidth=1, alpha=0.7)
    ax.axhline(y=efficiency_median, color='#555555', linestyle='--', linewidth=1, alpha=0.7)
    
    # Label quadrants with background boxes
    x_range = ax.get_xlim()
    y_range = ax.get_ylim()
    
    quadrant_labels = [
        # (x_pos_fraction, y_pos_fraction, text, fontcolor)
        (0.25, 0.75, 'Low Effort,\nHigh Impact\n(Star Performers)', '#2d7d46'),
        (0.75, 0.75, 'High Effort,\nHigh Impact\n(Keep & Reward)', '#1a5276'),
        (0.25, 0.25, 'Low Effort,\nLow Impact\n(Urgent Intervention)', '#922b21'),
        (0.75, 0.25, 'High Effort,\nLow Impact\n(Investigate Territory)', '#b7950b'),
    ]
    
    for x_frac, y_frac, text, color in quadrant_labels:
        x_pos = x_range[0] + x_frac * (x_range[1] - x_range[0])
        y_pos = y_range[0] + y_frac * (y_range[1] - y_range[0])
        ax.text(
            x_pos, y_pos, text,
            ha='center', va='center', fontsize=10, fontweight='bold',
            color=color, alpha=0.5,
            bbox=dict(boxstyle='round,pad=0.5', facecolor='white', alpha=0.3, edgecolor='none')
        )
    
    # Styling
    ax.set_xlabel('Visit Intensity (visits per HCP per month)', fontsize=13, fontweight='bold', labelpad=10)
    ax.set_ylabel('Efficiency Ratio (Actual Rx / Expected Rx)', fontsize=13, fontweight='bold', labelpad=10)
    ax.set_title('NovaMed — Rep Performance Quadrant Analysis',
                 fontsize=16, fontweight='bold', pad=15)
    
    # Subtitle annotation
    ax.text(
        0.5, 1.02,
        'Insight: Reps in the bottom-right quadrant work hard but in the wrong territories — prime candidates for redeployment',
        ha='center', va='bottom', transform=ax.transAxes,
        fontsize=10, fontstyle='italic', color='#666666'
    )
    
    ax.legend(title='Region', loc='upper left', framealpha=0.9, fontsize=10, title_fontsize=11)
    ax.grid(True, alpha=0.15, linestyle='-')
    ax.set_facecolor('#FAFAFA')
    fig.patch.set_facecolor('white')
    
    # Add reference line at efficiency_ratio = 1.0 (expected performance)
    ax.axhline(y=1.0, color='#333333', linestyle=':', linewidth=0.8, alpha=0.4)
    ax.text(
        x_range[0] + 0.01 * (x_range[1] - x_range[0]), 1.01,
        'Expected performance (1.0)',
        fontsize=8, color='#666666', fontstyle='italic'
    )
    
    plt.tight_layout()
    chart_path = os.path.join(CHARTS_DIR, 'rep_quadrant.png')
    fig.savefig(chart_path, dpi=150, bbox_inches='tight')
    plt.close(fig)
    print(f"\n  Chart saved to: {chart_path}")


# ============================================================================
# EXECUTION
# ============================================================================

if __name__ == '__main__':
    print("=" * 70)
    print("NovaMed SFE — Component 3: Rep Efficiency & Performance Quadrant")
    print("=" * 70)
    
    efficiency_df, visit_med, eff_med = compute_rep_efficiency()
    
    # Quadrant distribution
    print(f"\n--- Quadrant Distribution ---")
    quadrant_counts = efficiency_df['performance_quadrant'].value_counts()
    for quad, count in quadrant_counts.items():
        pct = count / len(efficiency_df) * 100
        print(f"  {quad:35s}: {count:>3} reps ({pct:.1f}%)")
    
    # Top and bottom reps by efficiency
    print(f"\n--- Top 5 Reps by Efficiency Ratio ---")
    top5 = efficiency_df.nlargest(5, 'efficiency_ratio')
    print(top5[['rep_name', 'city', 'region', 'efficiency_ratio', 'visit_intensity',
                'actual_rx', 'performance_quadrant']].to_string(index=False))
    
    print(f"\n--- Bottom 5 Reps by Efficiency Ratio ---")
    bottom5 = efficiency_df.nsmallest(5, 'efficiency_ratio')
    print(bottom5[['rep_name', 'city', 'region', 'efficiency_ratio', 'visit_intensity',
                   'actual_rx', 'performance_quadrant']].to_string(index=False))
    
    # High effort, low impact reps (the problem reps)
    problem_reps = efficiency_df[efficiency_df['performance_quadrant'] == 'High Effort, Low Impact']
    print(f"\n--- 'High Effort, Low Impact' Reps (investigate these) ---")
    print(f"  Count: {len(problem_reps)}")
    print(f"  Cities: {problem_reps['city'].value_counts().to_dict()}")
    
    # Generate chart
    print(f"\n--- Generating Performance Quadrant Chart ---")
    plot_quadrant(efficiency_df, visit_med, eff_med)
    
    print(f"\n  Saved: data/processed/rep_efficiency.csv")
    print(f"  Saved: data/processed/rep_quadrant.csv")
    print(f"  Saved: outputs/charts/rep_quadrant.png")
